package.json
=> fix: update nexus version 2.5.3

components/CartDetails/index.tsx, components/OrderSummaryBox/index.tsx, components/ProductFilterSort/index.tsx, locales/en.json, locales/id.json, package.json, pages/sitemap.xml.tsx, public/scss/components/CartDetails.module.scss, public/scss/components/OrderSummaryBox.module.scss, public/scss/utils/_colors.scss
=> feat:product notes & edit qty

components/Layout/Layout.tsx, components/SEO.tsx, pages/[lng]/index.tsx
=> fix: title website

package.json, pages/[lng]/payment_notif/[[...orderID]].tsx, public/scss/pages/PaymentNotif.module.scss, public/scss/pages/ThankYou.module.scss
feat: payment confirmation file upload improvement
- Update nexus version to 2.8.0
- Update file upload styling on 3 browsers
- Fix spacing on mobile device screens
URL Task: https://phabricator.sirclo.com/T30206
Pull Latest: OK
Build: OK (Local)
***
=> feat: payment confirmation file upload improvement

public/scss/components/OrderSummaryBox.module.scss
https://user-images.githubusercontent.com/8541505/159430520-b10a28fb-8836-44fc-825a-294ac014298e.mov
=> fix: edit quantity button

locales/en.json, locales/id.json
URL Task: 
**[MAKAR][delivery] oxphere : judul kategori artikel di template framic (locales'é salah)**
https://phabricator.sirclo.com/T30250
Build (Local): OK
Screenshot:
=> fix(articles): change article categories title

components/ProductsComponent/ProductsWidget.tsx
URL Task: https://phabricator.sirclo.com/T30379
URL PR: https://github.com/sirclo-solution/template-framic/pull/18
Pull Latest: OK
Build (Local): OK
Screenshots
=> fix(products): fix the see all link that caused the problem

components/Layout/Layout.tsx, components/OrderSummaryBox/index.tsx, components/SEO.tsx, locales/en.json, locales/id.json, package.json, pages/[lng]/payment_method/index.tsx, public/scss/components/OrderSummaryBox.module.scss
Screenshoot:
- [Empty Voucher](https://drive.google.com/file/d/1HGjMlUxc3oq0R3MTmyEFjPQ78SMMjcp4/view?usp=sharing)
- [Invalid Coupon](https://drive.google.com/file/d/1G1JciZdh36lNmb3O6AMTU7CBtD-c6STn/view?usp=sharing)
- [Valid Coupon](https://drive.google.com/file/d/1z2SxxrR5gYMnW8B3DIz45kLv0PP6UKC3/view?usp=sharing)
=> fix(OrderSummary): Invalid or valid popup coupon

package.json, public/scss/pages/Account.module.scss
=> chore: bump nexus version 2.11.4

pages/[lng]/payment_method/index.tsx, public/scss/components/Footer.module.scss, public/scss/components/OrderSummaryBox.module.scss, public/scss/pages/PaymentMethod.module.scss
-images.githubusercontent.com/93248829/171588988-3db49f13-8c2b-48
07-9436-8b02f9b1a1fe.png">
25-aec8-a02afb5d774d.png">
=> fix(orderSummary): Wrap long text coupon code

locales/id.json
Task: https://phabricator.sirclo.com/T33963
=> fix: wording editAccount

components/ProductFilterSort/index.tsx, public/scss/components/ProductSortFilter.module.scss
Task: https://phabricator.sirclo.com/T36904
Navigation menu
Limit list kategori di sidemenu jadi 15 & button load more
https://user-images.githubusercontent.com/28738321/186802004-7b87230f-d1ac-41ef-9d71-8fa436badf05.mov
=> fix: UI Fixing on Navigation menu

components/LoginRegisterOTP/index.tsx, components/OrderSummaryBox/index.tsx, locales/en.json, locales/id.json, package.json, pages/[lng]/payment_method/index.tsx, pages/[lng]/shipping_method/index.tsx, public/scss/components/LoginRegisterOTP.module.scss, public/scss/components/OrderSummaryBox.module.scss, public/scss/pages/ShippingMethod.module.scss, public/scss/utils/_colors.scss
- Desktop
- Mobile
- Functionality
- Desktop
- Mobile
- Loader Desktop
- Loader Mobile
- Loader at button apply coupon
- Desktop
- Mobile
=> feat: bump 2.13.3, add filter shipping, google sso button, and bank logo on coupon

locales/en.json, locales/id.json, pages/[lng]/legal/[slug].tsx, public/scss/pages/Legal.module.scss
Figma
https://www.figma.com/file/AMtQECMzDn4EXf4geUmzUI/%5BVENDOR%5D-Framic?node-id=29%3A1370
=> feat: legal module and disclaimer locales

components/OrderSummaryBox/index.tsx, locales/en.json, locales/id.json, pages/[lng]/payment_method/index.tsx, public/scss/components/OrderSummaryBox.module.scss
Mobile
Desktop
Kalo double voudher untuk shipper dan payment 
Voucher shipping di payment method
=> feat: Shipping logo on voucher popup

components/Footer/Footer.tsx, components/Layout/Layout.tsx, locales/en.json, locales/id.json, package.json, public/scss/components/Footer.module.scss
**Screenshots:**
- Starter plan
- Basic plan
- Pro plan
Note: tampilan mobile dempet kiri karena ada widget youtube
- Rejected order
Note: sudah confirm desainer untuk remove wording "DItempatkan pada"
=> feat: replace copyright component, add rejected order locales

public/scss/pages/Tautan.module.scss
https://user-images.githubusercontent.com/38358288/193505949-c816dc6c-419b-475a-9ddb-40f2dac210dd.mp4
=> fix(tautan): add max width for logo, add overflow auto for container

components/ProductDetailComponent/index.tsx, lib/useSizeBanner.ts
task: https://phabricator.sirclo.com/T40382
=> fix: increase image quality and size

components/Layout/Layout.tsx
=> fix(SEO): remove tag robots in template | T40781

components/ProductsComponent/ProductsWidget.tsx, components/ProductsComponent/index.tsx, locales/en.json, locales/id.json, package.json, pages/[lng]/account/index.tsx, pages/[lng]/index.tsx, pages/[lng]/products/[slug].tsx, public/scss/components/Banner.module.scss, public/scss/components/WidgetHomePage.module.scss
**Homepage**
Feature flag Product Highlight off:
Desktop
Mobile
Feature flag Product Highglight on:
Desktop
Mobile
**Product Highlight List Page**
Feature flag Product Highlight off:
Desktop
Mobile
Feature flag Product Highlight on:
Desktop
Mobile
**Penambahan locales dan toast**
=> chore: bump to 2.17.12, producthighlight featureflag

pages/[lng]/product/[slug].tsx
This is a test to check if the flicker problems in Product Detail Page can be solved using LazyLoadComponent wrapper.
Original Task: https://phabricator.sirclo.com/T42562
Note: No changes were found on local after implementing the Lazy Load wrapper. This solution is meant to be tested on staging because the problem could not be reproduced on local, yet persists in staging & prod environment.
=> fix(product-detail): test flicker lazyload solution

pages/_app.js
feature flag on and off:
https://user-images.githubusercontent.com/43097333/210760825-c1a25a20-35f2-4fd9-b233-df59051665e2.mov
https://user-images.githubusercontent.com/43097333/210760772-576f0b6e-c5c0-4c05-8af6-82af19461100.mov
=> fix(product-highlight): wrap parent component with TemplateFeatureFlag

components/ProductDetailComponent/index.tsx
Error in build caused by unused variable
=> fix: remove unused variable

components/LoginRegisterOTP/index.tsx, components/ProductDetailComponent/index.tsx, package.json, pages/[lng]/register/index.tsx
A revert from premium features that can be found [here](https://github.com/sirclo-solution/template-framic/pull/69).
The goal of this revert is to make sure the template version of beta-feature branch can be built on staging.
=>  fix: temporary revert premium features to 2.17.4

pages/[[...param]].tsx
Framic localhost run on nginx:
PoW:
(kiri before kanan after ditambahin `.replace()`)
=> fix(redirect): adjust redirect on file [[...param]].tsx

locales/en.json, locales/id.json, public/scss/pages/Account.module.scss
**Design review result**
1. Belum ada seperator di antara tanggal dan harga (vertlcally)
review:
fixing dikasi margin bottom:
2. Untuk penulisan complete payment before nya dibuat 1 line aja
review:
fixing dibuat `display: inline-flex`, sebelumnya pakai `max-width`:
=> fix(account): adjust order history styling and locales

components/Header/Header.tsx, public/scss/components/Header.module.scss, public/scss/components/ProductDetail.module.scss
Parent task: https://phabricator.sirclo.com/T42562
this is a test for flicker framic solution. Some solutions that were implemented are:
- Change header from fixed to sticky (to make scrolling smoother)
- Add webkit style for safari (got from online article regarding Safari scrolling bug)
Note: this solution has been tested on `beta-feature` branch and didn't solve the flickering, but will still be committed into master as a way to make sure all the solution tested are documented.
=> feat: implement sticky header and webkit for flicker test solution

locales/en.json, locales/id.json, package.json, public/scss/pages/PaymentMethod.module.scss
```
Notes
- Kedepannya akan ada fixing dari BE dueDateInDays nya jadi tidak required karena ada case jika tidak ada yang aktif pilihan ToP nya maka tidak ke hit upsertToPnya
```
Premium
Video : https://drive.google.com/file/d/1OzymsFX_bdfQp2LF8R2NmI_kig0zWFCI/view?usp=share_link
INDONESIA
ENGLISH
GQL
---
Non Premium
Video: https://drive.google.com/file/d/1OzymsFX_bdfQp2LF8R2NmI_kig0zWFCI/view?usp=share_link
=> feat(premium): add term of payment in payment method

locales/en.json
=> fix(PLP): fix clear locales still in indonesian

package.json
Sama seperti di pull request sebelumnya, tidak tersenggol dan masih berfungsi payment by term nya
=> chore(premium): update version to 2.18.19-beta.7

locales/en.json, locales/id.json, package.json, pages/[lng]/account/index.tsx, public/scss/pages/Account.module.scss
Figma:
https://www.figma.com/file/AMtQECMzDn4EXf4geUmzUI/%F0%9F%9F%A2-%5BVENDOR%5D-Framic?node-id=1301%3A18280&t=Q0nRMILR35vTzi6x-0
=> fix(account): style order history price detail & product notes and bump to 2.18.19

locales/en.json, locales/id.json, pages/[lng]/account/index.tsx, public/scss/pages/Account.module.scss
fix(account): style order history price detail & product notes and bump to 2.18.19
=> cherry-pick: Merge pull request #98 from ardiankristo/fix/order-history-price-detail-and-product-notes

locales/en.json, locales/id.json
- Change wording from `Pembayaran dengan termin` to `Pembayaran dengan Termin`
- Change wording from `Payment by term` to `Payment by Term`
ENGLISH
BAHASA
=> fix(premium): change ToP wording

locales/en.json
Cherry-pick commits from PR:
https://github.com/sirclo-solution/template-framic/pull/94
Sanity check:
Local build: OK
=> Release prod 20230227

locales/id.json, package.json, public/scss/pages/Account.module.scss
1. localesnya ID, tapi wordingnya Needs Review harusnya Butuh Ulasan/Sudah Diulas
2. valuenya Metode Pembayaran dan Metode Pengiriman belum bold
3. Perhitungan Subtotal harusnya tanpa Payment Fee
=> fix(account): fix product review locales & bump to 2.18.21

package.json
before : https://drive.google.com/file/d/1a3vkekxQvPNOGN3veELRiwQZzaf7vqd1/view?usp=share_link
after : https://drive.google.com/file/d/1Jd78uXMZtC5lKrVHUDKswRWn0r_-vHrv/view?usp=share_link
=> fix: session Expired and bump ver 2.18.23

pages/[lng]/register/index.tsx
Proof of work https://drive.google.com/file/d/1ckDk5AhPkp8f-b94O-NM5t6iUdZzxNSv/view?usp=share_link
=> fix(register): WA Input not displaying

components/ProductsComponent/ProductAll.tsx, components/ProductsComponent/index.tsx, pages/[lng]/index.tsx, public/scss/components/WidgetHomePage.module.scss
**Proof of Work**
| Case  | Desktop | Mobile |
| ------------- | ------------- | ------------- |
| Unleash Product Highlight **Active** & Categories **Active** & All Product **Active**  | ![image](https://user-images.githubusercontent.com/45877085/228799381-076c9396-9c9d-410b-9502-f1c2cb2a8cfb.png)  | ![image](https://user-images.githubusercontent.com/45877085/228799611-31674e17-e922-4909-b26e-58725a19a8ca.png)  |
| Unleash Product Highlight **Non Active** & Categories **Non Active** & All Product **Non Active** | ![image](https://user-images.githubusercontent.com/45877085/228800364-6ea24aee-181e-4acf-9b55-25a72cf9a726.png)  | ![image](https://user-images.githubusercontent.com/45877085/228800274-e53a814b-77d6-4393-92f2-a19291eb28ad.png)  |
| Unleash Product Highlight **Non Active** & …
=> feat: implement new settings for homepage

package.json
bump nexus version for https://github.com/sirclo-solution/template-framic/compare/master...iqbalwijonarko:template-framic:T47728/fix_nexus_version_for_homepage_new_settings?expand=1
=> chore: fix nexus version for new homepage settings

package.json
Task: https://phabricator.sirclo.com/T47996
=> chore: bump version nexus 2.18.21-beta.6

components/ProductDetailComponent/index.tsx, components/ProductsComponent/ProductHighlight.tsx, components/ProductsComponent/ProductRecomendation.tsx, components/ProductsComponent/ProductsList.tsx, components/ProductsComponent/ProductsWidget.tsx, components/ProductsComponent/index.tsx, pages/[lng]/cart/index.tsx, pages/[lng]/index.tsx, pages/[lng]/product/[slug].tsx, pages/[lng]/products/[slug].tsx, pages/[lng]/products/index.tsx, public/scss/components/CartDetails.module.scss, public/scss/components/OrderSummaryBox.module.scss, public/scss/components/Product.module.scss, public/scss/components/WidgetHomePage.module.scss
| Details  | Before | After |
| -------- | ------- | ------ |
| menyesuaikan warna font add to cart yang seharusnya hitam  |![image](https://user-images.githubusercontent.com/38358288/230256937-f2397159-27de-4b87-a938-c1c03d020b9e.png)  | ![image](https://user-images.githubusercontent.com/38358288/230257768-b0751ebf-f65d-49f4-a8a3-a727103aa76f.png)  |
| menghilangkan icon button delete pada proses checkout flow (place order)  | ![image](https://user-images.githubusercontent.com/38358288/230256972-fcf29cb8-871d-4e07-8b6c-8f014acdbfa8.png)  | ![image](https://user-images.githubusercontent.com/38358288/230258319-fd628723-2eac-4870-b665-5d9d2d17d2b2.png)  |
| menyesuaikan button continue shipping  | ![image](https://user-images.githubusercontent.com/38358288/230257045-0906db83-15ec-4fa3-bffb-0 …
=> fix: feedback from Maven

components/OrderSummaryBox/index.tsx, pages/[lng]/account/index.tsx, public/scss/components/CartDetails.module.scss
Proof of Work:
**Before**
for fixing remove item icon on order summary bug
for order status update after upload receipt
https://drive.google.com/file/d/1tsoTqnGZ7kPf5eZ_x26zCnt458_rfb-a/view?usp=sharing
**After**
for fixing remove item icon on order summary bug
for order status update after upload receipt
https://drive.google.com/file/d/1s2INkXIjuZCdeA_11V0daYXo1oo62mkg/view?usp=sharing
=> fix: fix order status update after upload receipt

locales/en.json, locales/id.json, package.json
Proof bump version, `for` nya label sudah punya id:
=> chore: bump to 2.18.33

components/ProductDetailComponent/index.tsx, components/ProductsComponent/ProductHighlight.tsx, components/ProductsComponent/ProductRecomendation.tsx, components/ProductsComponent/ProductsList.tsx, components/ProductsComponent/ProductsWidget.tsx, components/ProductsComponent/index.tsx, package.json, pages/[lng]/cart/index.tsx, pages/[lng]/index.tsx, pages/[lng]/product/[slug].tsx, pages/[lng]/products/[slug].tsx, pages/[lng]/products/index.tsx, public/scss/components/CartDetails.module.scss, public/scss/components/OrderSummaryBox.module.scss, public/scss/components/Product.module.scss, public/scss/components/WidgetHomePage.module.scss
Release consist of 
- Fix Feedback design from maven
- bump version 2.18.33
=> Release 20230413

components/OrderSummaryBox/index.tsx, components/ProductDetailComponent/index.tsx, components/ProductsComponent/ProductHighlight.tsx, components/ProductsComponent/ProductRecomendation.tsx, components/ProductsComponent/ProductsList.tsx, components/ProductsComponent/ProductsWidget.tsx, components/ProductsComponent/index.tsx, package.json, pages/[lng]/account/index.tsx, pages/[lng]/cart/index.tsx, pages/[lng]/index.tsx, pages/[lng]/product/[slug].tsx, pages/[lng]/products/[slug].tsx, pages/[lng]/products/index.tsx, public/scss/components/CartDetails.module.scss, public/scss/components/OrderSummaryBox.module.scss, public/scss/components/Product.module.scss, public/scss/components/WidgetHomePage.module.scss
included:
- [fix: fix order status update after upload receipt](https://github.com/sirclo-solution/template-framic/pull/128/commits/e6802e96d91fa33603e6f94e3870894bc49d2ca7)
- [fix: fix order summary remove button bug](https://github.com/sirclo-solution/template-framic/pull/128/commits/361918905c4f8a896af7537a05e5b1396fd22801)
=> Add PR 128 from master

package.json
* fix: show remove button in cart page
* add changes in index account
* bump 2.19.1 to solve custom shipping bugs
=> Bump 2.19.1 (#139)

components/ProductDetailComponent/index.tsx
Task: https://phabricator.sirclo.com/T49344
Test in ngrok: https://7d57-2001-448a-404b-1e5b-8d72-b7bf-e53d-4ea9.ngrok-free.app/en/product/luxeeflick
<html>
<body>
Item test | Proof of work
--  | -- 
Estimate Shipping  | ![Framic Theme - Luxee full flicker check - Google Chrome 17_05_2023 17_23_14](https://github.com/sirclo-solution/template-framic/assets/16263184/7c8484eb-49c0-458f-b5b0-e917048c300c) ![Framic Theme - Luxee full flicker check - Google Chrome 17_05_2023 17_23_26](https://github.com/sirclo-solution/template-framic/assets/16263184/c038d8a5-9bb1-4c77-8dbb-128bc1d6ccaa)
</body>
</html>	
<br class="Apple-interchange-newline">
=> fix(product-detail): show estimate shipping on production

components/OrderSummaryBox/index.tsx, locales/en.json, locales/id.json, public/scss/components/CheckoutComponent.module.scss, public/scss/components/OrderSummaryBox.module.scss
| Condition | Before | After 
|-----------|---------|------
| Desktop | ![image](https://github.com/sirclo-solution/template-framic/assets/38358288/85860601-f7d6-4c79-a20a-c75889106f7c) | ![image](https://github.com/sirclo-solution/template-framic/assets/38358288/69da78ec-6940-45c7-b745-722143195985)
| Mobile | ![image](https://github.com/sirclo-solution/template-framic/assets/38358288/d17006f9-0135-4c0e-b7f7-c0bbc702d698) | ![image](https://github.com/sirclo-solution/template-framic/assets/38358288/947facb5-9b78-4d9b-9bfd-ed43f29083ae)
| Not Enough Points Mobile |![image](https://github.com/sirclo-solution/template-framic/assets/38358288/ef35b689-116c-4037-bd3e-d878100b81eb) | ![image](https://github.com/sirclo-solution/template-framic/assets/38358288/6387d728-a964-4d91-afd2-5bc53deca5ee) …
=> Fix: Styling Pop Up Points

package.json
Data:
```
{
"paymentRecords": [
{
"status": "UNPAID",
"method": "credit_card",
"paymentOption": {
"paymentLink": "https://app.sandbox.midtrans.com/snap/v3/redirection/2eeb40c2-d35a-4023-8712-287ec75b956c",
"paymentToken": "2eeb40c2-d35a-4023-8712-287ec75b956c",
"vaNumber": "",
"qrString": "",
"qrImageLink": "",
"desktopPaymentLink": "https://app.sandbox.midtrans.com/snap/v3/redirection/2eeb40c2-d35a-4023-8712-287ec75b956c",
"mobilePaymentLink": "",
"__typename": "PaymentOption"
},
"provider": "midtranssnap",
"__typename": "PaymentRecord"
}
]
}
```
Video:
https://github.com/sirclo-solution/template-framic/assets/40454642/cbac8c09-d2b3-40c8-a56d-48ff88d0f2e1
=> chore: bump to 2.19.3

package.json
Cherry-pick commits from PR:
- https://github.com/sirclo-solution/template-framic/pull/152
**Local Build:**
**Template runs normally **
=> Release Prod 20230627- chore: bump version nexus 2.19.9

locales/en.json, locales/id.json, package.json, pages/[lng]/account/index.tsx, public/scss/pages/Account.module.scss
=> chore: bump nexus to 2.19.11-beta.1 and add styling for improvement need review status order

locales/en.json, locales/id.json, package.json, pages/[lng]/place_order/index.tsx, public/scss/components/MapLocation.module.scss, public/scss/pages/Placeorder.module.scss
<html>
<body>
Item test | Desktop | Mobile
--  | --  | -- 
Input phone  | ![image](https://github.com/sirclo-solution/template-framic/assets/16263184/dd6c42a3-f76d-457f-b613-17c4f0c29f01) | ![IMG_0690](https://github.com/sirclo-solution/template-framic/assets/16263184/fde94415-bfa9-49bb-8b5b-af9680f6340a)
Popup label detail address  | ![image](https://github.com/sirclo-solution/template-framic/assets/16263184/91acb44a-4fc0-4721-82d7-626123ebcede) | ![File (3)](https://github.com/sirclo-solution/template-framic/assets/16263184/a9c1bcc7-9d63-41b9-a494-bfbaafc9dc25) 
Direct co member  |  https://github.com/sirclo-solution/template-framic/assets/16263184/68de00bc-362c-47bd-a86e-db9c190001e1 | https://github.com/sirclo-solution/template-framic/assets/16263184/082c5dba-5c6b-4674-bd5e-f58185eced6 …
=> feat(place-order): revamp input phone, and styling in popup address

locales/en.json, locales/id.json, package.json, pages/[lng]/place_order/index.tsx, public/scss/components/MapLocation.module.scss, public/scss/pages/Placeorder.module.scss
Task For Release 
https://phabricator.sirclo.com/T51801
=> Release 20230830

components/ProductDetailComponent/index.tsx
Task : https://phabricator.sirclo.com/T54346
=> fix(ProductDetailComponent): change image quality to 85

components/ProductDetailComponent/index.tsx, pages/[lng]/index.tsx
=> Release 20230721

package.json
Task : https://phabricator.sirclo.com/T55229
=> chore: bump nexus 2.19.33
